[package]
name = "chwd"
version = "0.1.0"
authors = ["Vladislav Nepogodin <nepogodin.vlad@gmail.com>"]
license = "GPLv3"
edition = "2021"

[dependencies]
toml = "0.7.3"
libpci = { path = "libpci", version = "0.1.0" }
subprocess = "0.2.9"
colored = "2.0.0"
clap = { features = ["derive"], version = "4.2.4" }
anyhow = "1"
nix = { features = ["user"], default-features = false, version = "0.26.2" }
comfy-table = { default-features = false, version = "6.1.4" }

[profile.release]
strip = "symbols"
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
