[package]
name = "chwd"
version = "0.1.0"
authors = ["Vladislav Nepogodin <nepogodin.vlad@gmail.com>"]
license = "GPLv3"
edition = "2021"

[dependencies]
toml = "0.7.5"
libpci = { path = "libpci", version = "0.1.0" }
subprocess = "0.2.9"
colored = "2.0.0"
clap = { features = ["derive"], version = "4.3.9" }
anyhow = "1"
nix = { features = ["user"], default-features = false, version = "0.26.2" }
comfy-table = { default-features = false, version = "7.0.1" }
regex = "1.8.4"

[build-dependencies]
clap = { features = ["derive"], version = "4.3.9" }
clap_complete = "4.3.2"

[profile.release]
strip = "symbols"
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
